### ISSUE TITLE
String Formatting example on percentages has error

### ISSUE THREAD

**Issue by ajejoseph22** [karanpratapsingh/go-course#14]
**Problem**

In the String Formatting section, the example on percentages is wrong.
It says 

```
...
percent := (3/5) * 100
fmt.Printf("%f", percent)
...
```

and outputs the result as 
```
$ go run main.go
58.181818
```

This is wrong for 2 reasons.
1. 3/5 returns an integer `0` and go would complain about the type and formatting discrepancy (`%!f(int=0)`). 
2. Even if it were to be written as 3.0/5 (to have the value of `percent` be a float), that value would be `60.000000`, not `58.181818`
See playground [here](https://go.dev/play/p/hSXaRB-zKP7)

**Suggested solution**

For clarity, I suggest we use another example to illustrate this. See below

```
...
percent := (7.0 / 9) * 100
fmt.Printf("%f", percent)
...
```

```
$ go run main.go
77.777778 
```

and subsequently...
```
...
percent := (7.0 / 9) * 100
fmt.Printf("%.2f %%", percent)
...
```

```
$ go run main.go
77.78 %
```
See playground [here](https://go.dev/play/p/pshgcvVIjzN)

Links:
* https://www.karanpratapsingh.com/courses/go/string-formatting

**Comment by karanpratapsingh** [comment]
Thank you for the detailed explanation @ajejoseph22, I'll update it.

**Comment by ajejoseph22** [comment]
Have opened a PR for it here. https://github.com/karanpratapsingh/learn-go/pull/15

**Comment by karanpratapsingh** [comment]
Thanks @ajejoseph22, really appreciate it

**Comment by karanpratapsingh** [comment]
Merged! Thanks again
